### ISSUE TITLE
One-search-for-all

### ISSUE THREAD

**Issue by engganolang** [engganolang/enolex#14]
One search for all on the front page/main page

This means filtering the raw database.

Searching parameters:

- We can use the `filter(if_any(...))` combination.
- Word-boundary regex (`\\b`) capturing for the filter.
- Should normalise the input string as NFC (needs the stringi package).

Input parameters:
- text input for typing

Server parameters:
- the input is reactive.
- needs observer and `req()` to perform an output UI when this input is filled.

Output UI:
- would it be a table?
- TO CHECK: how to render output containing searched value being highlighted?

    - The search value being highlighted could be in a column
    - The server code needs to capture the row ID in which the value is found so that the ID can be used to later to act (e.g., generating a table) when the row of the respective ID is clicked in the output

**Comment by engganolang** [comment]
We deal with this using a different panel called `Global Search`

**Comment by gederajeg** [comment]
Fixed [here](https://github.com/engganolang/enolex/commit/9c1b7f7872e27091068e2c7e1011077aedf1dab8#r145310305)
