### ISSUE TITLE
Sources database

### ISSUE THREAD

**Issue by gederajeg** [engganolang/enolex#3]
A curated table for the sources/references of the lexical database:

- match the BibTeX key in the .bib file and the value of the `Sources` inside the EnoLEX main table

    - for this, following CLDF, do not use whitespace

- provide URL or DOI variable to each source when available
- a full citation format in `Unified style sheet for linguistics` (this needs to be generated via Zotero

    - for this part, check the part(s) of the title that needs to be italicised or quoted

**Comment by gederajeg** [comment]
A curated table for the sources/references of the lexical database:

- ~~match the BibTeX key in the .bib file and the value of the `Sources` inside the EnoLEX main table~~

    - ~~for this, following CLDF, do not use whitespace~~

- ~~provide URL or DOI variable to each source when available~~
- a full citation format in `Unified style sheet for linguistics` (this needs to be generated via Zotero

    - for this part, check the part(s) of the title that needs to be italicised or quoted

**Comment by engganolang** [comment]
A curated table for the sources/references of the lexical database:

- ~~match the BibTeX key in the .bib file and the value of the `Sources` inside the EnoLEX main table~~

    - ~~for this, following CLDF, do not use whitespace~~

- ~~provide URL or DOI variable to each source when available~~
- ~~a full citation format in `Unified style sheet for linguistics` (this needs to be generated via Zotero)~~ (we use the R code [here](https://github.com/engganolang/enolex/blob/main/codes/r-code_06-sources.R) and not necessarily in Unified style sheet for linguistics, though)

    - ~~for this part, check the part(s) of the title that needs to be italicised or quoted~~
