### ISSUE TITLE
Cognate colour-coding

### ISSUE THREAD

**Issue by gederajeg** [engganolang/enolex#5]
Try checking the colour coding of *cacaroa* ‘house’ (1894) that is the same with other forms of different cognate ID. Is that a bug? For the concept HOUSE, there are three cognate IDs sets and the colouring appears to be only two.

Steps:
- generate three colour based on the three cognate IDs
- check if the colour code is different for the three IDs
- If it does differ, consider exploring other more divergent palette.

**Comment by engganolang** [comment]
Fixed! Thanks
